echo "# Be4devth.com" >> README.md
git init
git add README.md
git commit -m "first commit"
git branch -M main
git remote add origin https://github.com/Skateug30/Be4devth.com.git
git push -u origin main
